### ISSUE TITLE
Problematic parsing

### ISSUE THREAD

**Issue by dagavi** [mancuniancol/script.pulsar.elitetorrent-mc#3]
This provider has problems with some common methods of your scripts:

Strict name check implies that correct results are blocked. For example, searching "Interstellar" (http://www.elitetorrent.net/busqueda/Interstellar/modo:listado/orden:valoracion):

```
WARNING: [script.pulsar.elitetorrent-mc] interstellar-ts-screener ***Blocked File by Name***
WARNING: [script.pulsar.elitetorrent-mc] interstellar-hdrip ***Blocked File by Name***
WARNING: [script.pulsar.elitetorrent-mc] interstellar-dvd-screener ***Blocked File by Name***
WARNING: [script.pulsar.elitetorrent-mc] interstellar-cam ***Blocked File by Name***
 NOTICE: [script.pulsar.elitetorrent-mc] >>>>>>0 torrents sent to Pulsar<<<<<<<
```

Results improve modifying common.py in verify:
`    if self.included(name, [self.title], True):`
for
`    if self.included(name, [self.title]):`

The other "problem" is the decision to append the language in the name. In non "generic" trackers (KickAss, piratebay...) its rare to have a name like "Interstellar Langugage" (Interstellar Español). The decission of add this code:
```
        if title == original_title:
            title += ' ' + keywords[language]
```
Breaks/deteriorates results (like Intersellar, for example) in this provider.

**Comment by mancuniancol** [comment]
Well,  the function is ok. It needs to be strict in the way not to get different results.  For example if you have a movie called happy days. If I do your suggestion, any movie with happy. Like happy years. Of the another day will be accepted. 

The problem is the provider is looking for interstellar español.  All the words.   As you mention, it is not way that it will find any results with español word. 

I will remove the Spanish word and then you will have results. I've added that when the title doesn't have translation in the language. But, in this site it is not that case.  Thanks for the feedback.

**Comment by dagavi** [comment]
The same "problem" (Add "Espa" in search) occurs in your divxatope provider (or "dixatope"): https://github.com/mancuniancol/script.pulsar.dixatope-mc

**Comment by mancuniancol** [comment]
Yes, I've noticed.  I've changed them too :)
To be honest, I don't use these providers and I depend from the people's feedback.  I am glad that you've noticed the problem.

Please, could you check if they are working properly now? version 3.0.1

**Comment by dagavi** [comment]
Results improve alot! (at least for Interstellar :) )
